enum ResponseMessage {
  SUCCESS = "SUCCESS",

  VALIDATION_FAIL = "VALIDATION_FAIL",

  DUPLICATED_ID = "DUPLICATED_ID",

  SIGN_IN_FAIL = "SIGN_IN_FAIL",

  CERTIFICATION_FAIL = "CERTIFICATION_FAIL",

  DATABASE_ERROR = "DATABASE_ERROR",

  MAIL_SEND_FAIL = "MAIL SEND FAILED",
}

export { ResponseMessage };
